### ISSUE TITLE
Cannot build due to nonexistent Musashi commit and missing files

### ISSUE THREAD

**Issue by halian** [InvisibleUp/uvmac#2]
Currently, attempting to clone the repository fails with the following error:

```
fatal: remote error: upload-pack: not our ref 67346dba6d245d48ab362dfa1d2c18075f9fbcf1
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'src/HW/M68K', but it did not contain 67346dba6d245d48ab362dfa1d2c18075f9fbcf1. Direct fetching of that commit failed.
```

This can be overcome by manually cloning Musashi into that directory, but doing so causes Meson to fail to initialize the directory for building on account of `m68khooks.c` and `m68kops.c` being absent.

**Comment by InvisibleUp** [comment]
Fixed. Apologies for the time this took.

**Comment by halian** [comment]
meson.build:175:0: ERROR: File lib/M68K/m68kops.c does not exist.
