### ISSUE TITLE
Require -z muldefs to build

### ISSUE THREAD

**Issue by Nadihat** [InvisibleUp/uvmac#7]
I had to add "-z muldefs" in the build.ninja file, linker arguments:
rule c_LINKER
 command = cc $ARGS -o $out $in $LINK_ARGS -z muldefs
 description = Linking target $out
Otherwise it creates many errors:
/usr/bin/ld: microvmac.p/src_HW_SCREEN_SCRNEMDV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: multiple definition of `UseLargeScreenHack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: first defined here
/usr/bin/ld: microvmac.p/src_HW_SCREEN_SCRNEMDV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: multiple definition of `ScreenColorBlack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: first defined here
/usr/bin/ld: microvmac.p/src_HW_SCREEN_SCRNEMDV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: multiple definition of `ScreenColorWhite'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: first defined here
/usr/bin/ld: microvmac.p/src_PATCHES_SCRNHACK.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: multiple definition of `UseLargeScreenHack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: first defined here
/usr/bin/ld: microvmac.p/src_PATCHES_SCRNHACK.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: multiple definition of `ScreenColorBlack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: first defined here
/usr/bin/ld: microvmac.p/src_PATCHES_SCRNHACK.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: multiple definition of `ScreenColorWhite'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: first defined here
/usr/bin/ld: microvmac.p/src_UI_COMOSGLU.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: multiple definition of `UseLargeScreenHack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:35: first defined here
/usr/bin/ld: microvmac.p/src_UI_COMOSGLU.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: multiple definition of `ScreenColorBlack'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:36: first defined here
/usr/bin/ld: microvmac.p/src_UI_COMOSGLU.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: multiple definition of `ScreenColorWhite'; microvmac.p/src_PATCHES_SONYDRV.c.o:/home/reden/Downloads/uvmac/build/../src/HW/SCREEN/SCRNEMDV.h:37: first defined here
/usr/bin/ld: microvmac.p/src_UI_CONTROLM.c.o:/home/reden/Downloads/uvmac/build/../src/UI/COMOSGLU.h:83: multiple definition of `PbufAllocatedMask'; microvmac.p/src_UI_COMOSGLU.c.o:/home/reden/Downloads/uvmac/build/../src/UI/COMOSGLU.h:83: first defined here
/usr/bin/ld: microvmac.p/src_UI_CONTROLM.c.o:/home/reden/Downloads/uvmac/build/../src/UI/COMOSGLU.h:84: multiple definition of `PbufSize'; microvmac.p/src_UI_COMOSGLU.c.o:/home/reden/Downloads/uvmac/build/../src/UI/COMOSGLU.h:84: first defined here

And so forth. This seems to affect all OSes including OpenBSD 7.4 and Arch Linux.

**Comment by InvisibleUp** [comment]
Ah, right. The problem is that I'm declaring those variables in the header files, and GCC/Clang really don't like that. I'd need to declare then as `extern` and move the actual definition to the associated C file. Should be a simple fix. (I've been working with MSVC lately, so I guess that hasn't been an issue for me.)

**Comment by InvisibleUp** [comment]
Build works OK on Linux for me after fix.
